name: Check Commit Message

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  validate-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validar Mensagem
        run: |
          # Captura a última mensagem
          MSG=$(git log -1 --pretty=%B)
          echo "Mensagem enviada: $MSG"
          
          # Se a mensagem for apenas um ponto ou tiver menos de 3 caracteres
          if [[ "$MSG" == "." ]] || [ ${#MSG} -lt 3 ]; then
            echo "ERRO: Mensagem irrelevante detectada!"
            exit 1
          fi
          echo "Mensagem aprovada!"
          