name: Validar Estrutura

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Listar arquivos na raiz
        run: ls -R
        
      - name: Confirmar que o projeto foi carregado
        run: echo "O projeto foi carregado com sucesso no GitHub Actions!"